INSERT INTO users (fullname, username, email, password) VALUES
('John Doe', 'johndoe', 'john@example.com', '1234'),
('Jane Smith', 'janesmith', 'jane@example.com', '1234'),
('Mike Johnson', 'mikejohnson', 'mike@example.com', '1234');

INSERT INTO CharacterClasses (class_name) VALUES 
('Warrior'),
('Rogue'),
('Archer'),
('Wizard');

INSERT INTO UserProfiles (user_id, warrior_experience, warrior_level, rogue_experience, rogue_level, archer_experience, archer_level, wizard_experience, wizard_level) VALUES
(1, 0, 1, 0, 1, 0, 1, 0, 1),
(2, 0, 1, 0, 1, 0, 1, 0, 1),
(3, 0, 1, 0, 1, 0, 1, 0, 1);




INSERT INTO Workouts (class_id, workout_type, difficulty, duration, sets_reps, description) VALUES
-- Warrior Workouts
(1, 'Bench Press', 'Easy', 7.5, '3x10', 'A fundamental exercise for upper body strength.'),
(1, 'Squats', 'Easy', 7.5, '3x10', 'A lower body exercise that targets the legs and glutes.'),
(1, 'Incline Dumbbell Press', 'Easy', 7.5, '3x10', 'Targets the upper chest and shoulders.'),
(1, 'Dumbbell OverHead Press', 'Easy', 7.5, '3x10', 'A shoulder exercise that improves upper body strength.'),
(1, 'Triceps Pushdown', 'Easy', 7.5, '3x10', 'Isolates the triceps muscles for growth and strength.'),
(1, 'Lat Pulldown', 'Easy', 7.5, '3x10', 'Targets the latissimus dorsi muscles in the back.'),
(1, 'Leg Press', 'Easy', 7.5, '3x10', 'A machine exercise for the lower body.'),
(1, 'Barbell Curl', 'Easy', 7.5, '3x10', 'An isolation exercise for the biceps.'),
(1, 'Seated Row', 'Easy', 7.5, '3x10', 'Targets the middle back and biceps.'),
(1, 'Deadlift', 'Medium', 7.5, '3x10', 'A compound exercise for overall body strength.'),
(1, 'Leg Extension', 'Medium', 7.5, '3x10', 'Isolates the quadriceps.'),
(1, 'Chest Fly', 'Medium', 7.5, '3x10', 'Targets the chest muscles.'),
(1, 'Tricep Dip', 'Medium', 7.5, '3x10', 'A bodyweight exercise for triceps strength.'),
(1, 'Calf Raise', 'Medium', 7.5, '3x10', 'Isolates the calf muscles.'),
(1, 'Hammer Curl', 'Medium', 7.5, '3x10', 'Targets the biceps and forearms.'),
(1, 'Shoulder Press', 'Medium', 7.5, '3x10', 'Strengthens the shoulders.'),
(1, 'Incline Bench Press', 'Medium', 7.5, '3x10', 'Focuses on the upper chest.'),
(1, 'Pull-Ups', 'Medium', 7.5, '3x10', 'A bodyweight exercise for upper body strength.'),
(1, 'Power Clean', 'Hard', 7.5, '3x10', 'A full-body explosive movement.'),
(1, 'Snatch', 'Hard', 7.5, '3x10', 'An Olympic weightlifting exercise.'),
(1, 'Front Squat', 'Hard', 7.5, '3x10', 'A variation of the squat targeting the quads.'),
(1, 'Overhead Squat', 'Hard', 7.5, '3x10', 'Combines a squat with an overhead press.'),
(1, 'Push Press', 'Hard', 7.5, '3x10', 'A compound movement involving shoulders and legs.'),
(1, 'Bent Over Row', 'Hard', 7.5, '3x10', 'Targets the back muscles.'),
(1, 'Weighted Pull-Ups', 'Hard', 7.5, '3x10', 'Pull-ups with added weight.'),
(1, 'Rack Pull', 'Hard', 7.5, '3x10', 'A partial deadlift.'),
(1, 'Bulgarian Split Squat', 'Hard', 7.5, '3x10', 'A single-leg exercise targeting the legs.'),

-- Rogue Workouts
(2, 'Standing Calf', 'Easy', 7.5, '3x10', 'Targets the calf muscles.'),
(2, 'Staggered Hamstring Stretch', 'Easy', 7.5, '3x10', 'Improves hamstring flexibility.'),
(2, 'Figure-Four Stretch', 'Easy', 7.5, '3x10', 'Targets the glutes and hips.'),
(2, 'Seated Quad Stretch', 'Easy', 7.5, '3x10', 'Improves quadriceps flexibility.'),
(2, 'Child’s Pose', 'Easy', 7.5, '3x10', 'A relaxing yoga pose for the back.'),
(2, 'Downward Dog', 'Easy', 7.5, '3x10', 'A yoga pose targeting the whole body.'),
(2, 'Butterfly Stretch', 'Easy', 7.5, '3x10', 'Targets the inner thighs.'),
(2, 'Cat-Cow Stretch', 'Easy', 7.5, '3x10', 'Improves spine flexibility.'),
(2, 'Tricep Stretch', 'Easy', 7.5, '3x10', 'Stretches the triceps.'),
(2, 'Dynamic Lunges', 'Medium', 7.5, '3x10', 'A dynamic stretch for the legs.'),
(2, 'Hip Flexor Stretch', 'Medium', 7.5, '3x10', 'Targets the hip flexors.'),
(2, 'IT Band Stretch', 'Medium', 7.5, '3x10', 'Improves IT band flexibility.'),
(2, 'Pigeon Pose', 'Medium', 7.5, '3x10', 'A deep stretch for the hips.'),
(2, 'Standing Hamstring Stretch', 'Medium', 7.5, '3x10', 'Improves hamstring flexibility.'),
(2, 'Thoracic Spine Stretch', 'Medium', 7.5, '3x10', 'Targets the thoracic spine.'),
(2, 'Wall Sit', 'Medium', 7.5, '3x10', 'An isometric exercise for the legs.'),
(2, 'Calf Stretch', 'Medium', 7.5, '3x10', 'Improves calf flexibility.'),
(2, 'Side Stretch', 'Medium', 7.5, '3x10', 'Targets the obliques.'),
(2, 'Russian Twists', 'Hard', 7.5, '3x10', 'Targets the obliques.'),
(2, 'Plyometric Lunges', 'Hard', 7.5, '3x10', 'A dynamic exercise for the legs.'),
(2, 'Banded Walk', 'Hard', 7.5, '3x10', 'Targets the glutes and legs.'),
(2, 'Inchworms', 'Hard', 7.5, '3x10', 'A full-body dynamic stretch.'),
(2, 'Plank Walkouts', 'Hard', 7.5, '3x10', 'Combines a plank with a dynamic movement.'),
(2, 'Single-Leg Deadlift', 'Hard', 7.5, '3x10', 'Targets the hamstrings and glutes.'),
(2, 'Windmill Stretch', 'Hard', 7.5, '3x10', 'A dynamic stretch for the whole body.'),
(2, 'Scorpion Stretch', 'Hard', 7.5, '3x10', 'Targets the back and hips.'),
(2, 'Lateral Lunge', 'Hard', 7.5, '3x10', 'Targets the inner and outer thighs.'),

-- Archer Workouts
(3, 'Running', 'Easy', 7.5, '3x10', 'A cardiovascular exercise.'),
(3, 'HIIT', 'Easy', 7.5, '3x10', 'High-intensity interval training.'),
(3, 'Cycling', 'Easy', 7.5, '3x10', 'A low-impact cardiovascular exercise.'),
(3, 'Jumping Rope', 'Easy', 7.5, '3x10', 'A full-body cardiovascular exercise.'),
(3, 'Stair Climbing', 'Easy', 7.5, '3x10', 'Targets the legs and glutes.'),
(3, 'Swimming', 'Easy', 7.5, '3x10', 'A low-impact full-body exercise.'),
(3, 'Rowing', 'Easy', 7.5, '3x10', 'Targets the back and legs.'),
(3, 'Elliptical', 'Easy', 7.5, '3x10', 'A low-impact cardiovascular exercise.'),
(3, 'Power Walking', 'Easy', 7.5, '3x10', 'A low-impact cardiovascular exercise.'),
(3, 'Interval Running', 'Medium', 7.5, '3x10', 'Combines running with walking.'),
(3, 'Circuit Training', 'Medium', 7.5, '3x10', 'A combination of strength and cardio exercises.'),
(3, 'Boxing', 'Medium', 7.5, '3x10', 'A full-body cardiovascular exercise.'),
(3, 'Dancing', 'Medium', 7.5, '3x10', 'A fun cardiovascular exercise.'),
(3, 'Zumba', 'Medium', 7.5, '3x10', 'A high-energy dance workout.'),
(3, 'Aerobics', 'Medium', 7.5, '3x10', 'A full-body cardiovascular exercise.'),
(3, 'Speed Skating', 'Medium', 7.5, '3x10', 'A high-intensity cardiovascular exercise.'),
(3, 'Kickboxing', 'Medium', 7.5, '3x10', 'A full-body cardiovascular exercise.'),
(3, 'Mountain Climbers', 'Medium', 7.5, '3x10', 'A full-body cardiovascular exercise.'),
(3, 'Sprinting', 'Hard', 7.5, '3x10', 'A high-intensity cardiovascular exercise.'),
(3, 'Battle Ropes', 'Hard', 7.5, '3x10', 'A full-body cardiovascular exercise.'),
(3, 'Plyometrics', 'Hard', 7.5, '3x10', 'A high-intensity cardiovascular exercise.'),
(3, 'CrossFit', 'Hard', 7.5, '3x10', 'A combination of strength and cardio exercises.'),
(3, 'Treadmill Sprints', 'Hard', 7.5, '3x10', 'A high-intensity cardiovascular exercise.'),
(3, 'Spinning', 'Hard', 7.5, '3x10', 'A high-intensity cardiovascular exercise.'),
(3, 'Burpees', 'Hard', 7.5, '3x10', 'A full-body cardiovascular exercise.'),
(3, 'Squat Jumps', 'Hard', 7.5, '3x10', 'A high-intensity cardiovascular exercise.'),
(3, 'Box Jumps', 'Hard', 7.5, '3x10', 'A high-intensity cardiovascular exercise.'),

-- Wizard Workouts
(4, 'Squats', 'Easy', 7.5, '3x10', 'A lower body exercise that targets the legs and glutes.'),
(4, 'Burpee', 'Easy', 7.5, '3x10', 'A full-body exercise that combines a squat, plank, and jump.'),
(4, 'Pushups', 'Easy', 7.5, '3x10', 'A bodyweight exercise that targets the chest, shoulders, and triceps.'),
(4, 'Lunge', 'Easy', 7.5, '3x10', 'A lower body exercise that targets the legs and glutes.'),
(4, 'Glute Bridge', 'Easy', 7.5, '3x10', 'A lower body exercise that targets the glutes and hamstrings.'),
(4, 'Plank', 'Easy', 7.5, '3x10', 'A core exercise that targets the abdominals.'),
(4, 'Superman', 'Easy', 7.5, '3x10', 'A lower back exercise.'),
(4, 'Bicycle Crunch', 'Easy', 7.5, '3x10', 'A core exercise that targets the abdominals.'),
(4, 'Jumping Jacks', 'Easy', 7.5, '3x10', 'A full-body cardiovascular exercise.'),
(4, 'Dips', 'Medium', 7.5, '3x10', 'A bodyweight exercise that targets the triceps.'),
(4, 'Wall Sit', 'Medium', 7.5, '3x10', 'An isometric exercise for the legs.'),
(4, 'Leg Raise', 'Medium', 7.5, '3x10', 'A core exercise that targets the abdominals.'),
(4, 'High Knees', 'Medium', 7.5, '3x10', 'A cardiovascular exercise that targets the legs.'),
(4, 'Mountain Climbers', 'Medium', 7.5, '3x10', 'A full-body cardiovascular exercise.'),
(4, 'Tricep Dip', 'Medium', 7.5, '3x10', 'A bodyweight exercise that targets the triceps.'),
(4, 'Reverse Crunch', 'Medium', 7.5, '3x10', 'A core exercise that targets the abdominals.'),
(4, 'Step-Ups', 'Medium', 7.5, '3x10', 'A lower body exercise that targets the legs and glutes.'),
(4, 'Bridge', 'Medium', 7.5, '3x10', 'A lower body exercise that targets the glutes and hamstrings.'),
(4, 'Handstand Pushups', 'Hard', 7.5, '3x10', 'A bodyweight exercise that targets the shoulders.'),
(4, 'One-Legged Squat', 'Hard', 7.5, '3x10', 'A lower body exercise that targets the legs and glutes.'),
(4, 'Planche', 'Hard', 7.5, '3x10', 'A full-body isometric exercise.'),
(4, 'Pistol Squat', 'Hard', 7.5, '3x10', 'A lower body exercise that targets the legs and glutes.'),
(4, 'Dragon Flag', 'Hard', 7.5, '3x10', 'A core exercise that targets the abdominals.'),
(4, 'Human Flag', 'Hard', 7.5, '3x10', 'A full-body isometric exercise.'),
(4, 'Iron Cross', 'Hard', 7.5, '3x10', 'A full-body isometric exercise.'),
(4, 'Muscle-Up', 'Hard', 7.5, '3x10', 'A bodyweight exercise that targets the upper body.'),
(4, 'V-Sit', 'Hard', 7.5, '3x10', 'A core exercise that targets the abdominals.');